##################################
#
# Makefile for UIUC
#
##################################

CPP = g++
CPPFLAGS= -Wall -Werror

all: main

main: main.cpp
	$(CPP) $(CPPFLAGS) main.cpp -o main.o

clean:
	rm main.o
